language: java
jdk: oraclejdk8
sudo: required
services: docker
env:
  global:
  - secure: gNa24fKqQYNc+qvK4+XMYU8etZOoitWkoYtOW8ZOcw4NG0So9t3U8SqLlFi/1NjxqLiSTn6XY8h1+CNS7aEQ7OZgL+YfgoZ04DW+hOjka7THLuff9Ks5MFDZfEriyD+4WhLijif1mNojZPXb+p3uENMJcY2zBxwnfJUE2ZFeuAuTehJhDt1sOzA3XFn3D1dxuc7xTkfI9sDMk1XST/CpuKUI9j6+l5Qb/NG9Npj5HH46mJ07M81abBdFUwrEIgOuVpqk4EFxp6OeeDJFA+dVbKcYFgNnPfn3njfZmfSxh+04qFj/U5Ox1YxSQK3/xJHvUuiQGoBqmuQUvZufL3j91NtGR9pszGWq/Dw6a4K4bxqibaBu9bFPP/tlCbvn+K46AZF5UKynXl2xrr44XG5j/jsrEYJiZMNW56aD8dfkmqnGC9pV9o/O/4MzdNL+wLsUh8g3vrTvY/sDGeifL4+HdG1Avzml6AmGl3BCSF1yd2jQ+7cb5Wca0HlIr1w3GGlT+hhmojD1LMRdKJ3oJuVXNamtsrDwrvJBMQxmj5C8iwaCXSglZDlFPpH5oJmTOxoXr5rGEI/DZkVoi3zcUhfiYynHfGZsCawxf1SMDE+97RQoq4wg+PdS8/xNkSp0RCepKMNL8moSbR+URp3aaJnVg/B4RkQMtPZt3/oPVQMefKE=
  - secure: Xbi6TUeydRlGSt+43xN3qv/wagjW/PCmKnTsauW5xEpVqwT5nD9tg/0epuhVGGUi0ZzHrWgQrSbW+satbD3XB9zq1SVAMnl2GfJiYFQTk+DrbouR8g4DaxNonyicPNSHmeUornZWok0P7iKmscB9wGQ9DS4Vvz0DeGI+RcOfGevUXDmHV0nVvBDqsK7kcfGBqyGlqk13Yz1koLFvCh1OO2fh8wESxW+S1yGH2H04TaUFnF4G5oa8/Zgk+95Bw80aKTYasBrb6RnDS6O7T8TrydYpRyh+3p2IBEi3jgrx5Y2nsXqlSiM8kmPp9bylN3K9qFWJ+bYf5U49M5kmZFfNdb9Ote/57ibHdno7xE1prvp5pImj3GmAnvdfWVoKKSi/WxIwIlMbvaqi4Fyqj0BNBxuFhkNaRn9GnPFMrC3q5a9RQMsycuMigpjYmT0e1sLBzE3VospQDmPo5mMr118W3Jkn9wwlDodN52z9ix/e62W7wFDEENY1FOuIM3FLHChQrpWcZJCyvKezfZll6in1RF3VcesKOcgjTZAppBG0pMUs61NW9RahIDRRqIEaEc7jRXsV+JQ493FaQMPBBbqqOThRl/SmiDg7kEKoypTkPoV8diGIzvGDnuWWZs0zm0D9Su8Yw0/7aKHQCPXbawbQbrNoQzD8VypoG6eo4r9NZtY=
  - secure: anqGFWjK414m4zjJEIjedipfeTGjq/kiasLN8x1umXX+HnissuAKLjTCwyw6p6+RVTpxHAuLyOT2XyJHwLm8aAhlpzQxo8z/KLTwz4VDtM5QgqnUrRW4lK2SQGRhOcNaPQ53cJhGnYZYh7hmdXlxHHUjLC1lpXxl67uAqnKoixEgNGuu2c8dHBEFT3dsv+aCbFWtKBFfU9lAdL0vCmo32ey2dhpnk/3QRm/I7Aw7wF72ttggqrlxVzxb+XwD76t45g0Hzgsmd/NqYHOJcrai542csXDjlR7Fb/bD2C+A2jVssK6XQmKo34nqtLchLGLST9mOJdrGSisWUXGx9dV8qTLZ4/97DqWZ2erZGfC0UPhANBL2aVxoOiTTK47TNV4wwSbKAaDEbY6RGG10EJ1rtE0sECHRTpNJ9eXpgu7XrJF0HfGNZPDlijkSO89hsbNln6DN83+TBx1GsELemvS5g6zhH5LT/jOh9elVJm/ZW7al2igfN/E2cbRYoJGgNmOTNW+aMuS4bu2N2vZojNDW/4ousd4R0TZod9s/Ns4QkvNnAsPwHsyMZboK0XOW12RGbHZXALrNm8TQ46W2KCnMlFqhKd8U+QJ5tA+Sy9eyYcAto4sRTGzTYtNNwHmb5oe6eNT0yhYmllevSWNqUTkHo8mP0SrT1htU26otjPhPHGU=
  - secure: DOZaP65wr1ERNmU68ZK2x1YlCJrnf/x+irtBMJxwIeIFkFvITfPeVyahQ4+qwmlI5JVdGTi2IEam+eXEQ7hzY4Z5hAqOPNUafSm9ynWnly3NopuBcgD/0cVo97LzUSisWEqqJJrIN6FqlVIcJ6SPM2EaQhl5rAwlj2VHP65qr+Epa0p6avwIPH51T7kTc/9bDMHiJ1aLRibUNq6JGQMjnJf9+EQNFh1WPjuuzGjrh3ZQ5sjs2cK8gytBAnv4LV/N57HG7bwyUuPgd5pjHul/KA5boTJUhKfoRBisNC0RkFOusS8INOkXVDS1N3g2W7mwa5TL12zSb1biy7pD7nXy6/Tj7yI5FXcaLKraUbzHURkTrkI0sOpRj0I2csNbZVISPpxPNGTHoZJ/pde6hkMEilrEMTLWHpPNuRaQvlU8kzK8IV5TC4MNLJL2f4b1UNcLfoTJ4e0/HhKsvo66AVXexjy5uY1DhXUKe6KqnRTMSJTwO5I5F+vLEd4Lf5HJb6XiCDe19iXwKO8Ow86xK6o7KEmfHWlFqfKxTEKjpGtUZGO6XtHCLE353NRdjtHEeuVjnu1Tfs4LKWBccOvqLUqtvIttT1j7oOwOTbdQJKLKIeHTTWXe8i3L517I9EhYvTWW3j0ACD193vq6l2ZendFh/uIBSYGpZ4ws3Iwwa9Z/FFA=
  - secure: XfWZrFmruMiCazTmGp3r/zYTAw/l61HfLRxWVnfa7PnEeGy24+98HXOIFaKWoSHocrLfoweqTjUKL3kT2c4o0Cvv9gmn914oL0i7AGSxzA014yJknSDUWMp6wpQFuzgMpRKMoISiuWcX44IQqdb4wmpIXBC4MFoN2i3EdCfWcPAQXWJBpppqYL6ek4ORmg+xTXci6HWnabhzFusHMcxo4JBvq/h3xCS7jAygbi8WbLBw/TZzcD/HuFRimj7u+XJ0Ti/bEpCHiSMqBWcs9JOEd2o/FvMdL/NGIFHJSS2m9G4X1QBBinR0tmd97SVMwRqDLGrcNBAPzHN1wa4j18BiIdXkkO09NhArZHtyDA6Jo43tfEJfL8RqpGouSFmGD6dKpqlJrzxBIzNHiU7wwneoakeXhdOHcIT8bVO6s7W8pZPWy0XDLYHJQNgo1yNziwDfYgqvucG8jgfrQsR5tUow3Ug+AG+cjvpnRAGMY9VrHc+TmFwgYn4dfmi2UrVvB9NroPvUSVtcJsDMiEGqolsOXaWvEdUkc2ewHMsTd5al2YOgtLoI4As7xqVAN/DiKMADOZeHXAo3cXDXlClu1nAwPRSqwAhiY0oSZzsEAFTJviRCRgLVT7DKbEjtARgVJJF0bXY1MAWN+8NLNXuHls1EAsr4Wiczty7XP22UENOccXo=
  - COMMIT=${TRAVIS_COMMIT::7}
branches:
  only:
  - master
before_install:
  - chmod +x mvnw
script:
- "./mvnw clean install -B"

cache:
  directories:
    - '$HOME/.m2/repository'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=murat/travistutorial
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: travistutorial